const mongoose = require("mongoose");

/*
 * ============================================================
 * EDUCATOR QUESTION BANK
 * ============================================================
 *
 * Central question bank for the new Educator EMS.
 *
 * Questions are NOT tied directly to one exam.
 *
 * A question can therefore be reused across different exams,
 * students and batches where permitted.
 *
 * Repeat protection is handled separately by
 * EducatorQuestionUsage.
 * ============================================================
 */

const optionSchema = new mongoose.Schema(
  {
    key: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
      maxlength: 5,
    },

    text: {
      type: String,
      required: true,
      trim: true,
      maxlength: 5000,
    },
  },
  {
    _id: false,
  },
);

const educatorQuestionSchema = new mongoose.Schema(
  {
    /*
     * ========================================================
     * QUESTION IDENTITY
     * ========================================================
     */

    questionCode: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
      maxlength: 100,
    },

    /*
     * Stable fingerprint generated by the backend.
     *
     * Used to identify materially duplicate questions even
     * when their teacher-provided question IDs differ.
     */
    questionHash: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },

    questionText: {
      type: String,
      required: true,
      trim: true,
      maxlength: 10000,
    },

    /*
     * ========================================================
     * QUESTION TYPE
     * ========================================================
     */

    questionType: {
      type: String,
      enum: [
        "MCQ",
        "TRUE_FALSE",
        "MULTIPLE_SELECT",
        "NUMERICAL",
        "SHORT_ANSWER",
        "LONG_ANSWER",
      ],
      default: "MCQ",
      index: true,
    },

    /*
     * ========================================================
     * OPTIONS
     * ========================================================
     */

    options: {
      type: [optionSchema],
      default: [],
    },

    /*
     * For MCQ this contains one key.
     *
     * For MULTIPLE_SELECT this can contain multiple keys.
     *
     * Stored server-side and never exposed through the
     * student exam-start response.
     */
    correctAnswers: {
      type: [String],
      default: [],
      select: false,
    },

    /*
     * ========================================================
     * EXPLANATION
     * ========================================================
     */

    explanation: {
      type: String,
      default: "",
      trim: true,
      maxlength: 10000,
      select: false,
    },

    /*
     * ========================================================
     * CLASSIFICATION
     * ========================================================
     */

    subject: {
      type: String,
      required: true,
      trim: true,
      maxlength: 150,
      index: true,
    },

    topic: {
      type: String,
      default: "",
      trim: true,
      maxlength: 200,
      index: true,
    },

    subtopic: {
      type: String,
      default: "",
      trim: true,
      maxlength: 200,
    },

    difficulty: {
      type: String,
      enum: [
        "EASY",
        "MEDIUM",
        "HARD",
      ],
      default: "MEDIUM",
      index: true,
    },

    /*
     * ========================================================
     * MARKING
     * ========================================================
     */

    defaultMarks: {
      type: Number,
      default: 1,
      min: 0,
    },

    defaultNegativeMarks: {
      type: Number,
      default: 0,
      min: 0,
    },

    /*
     * ========================================================
     * SOURCE INFORMATION
     * ========================================================
     *
     * Designed for the teacher PDF/Word/Excel importer.
     */

    sourceType: {
      type: String,
      enum: [
        "MANUAL",
        "PDF",
        "DOCX",
        "XLSX",
        "XLS",
        "IMPORT",
      ],
      default: "MANUAL",
    },

    sourceFileName: {
      type: String,
      default: "",
      trim: true,
    },

    sourceSection: {
      type: String,
      default: "",
      trim: true,
    },

    sourceRow: {
      type: Number,
      default: null,
      min: 1,
    },

    /*
     * ========================================================
     * OWNERSHIP
     * ========================================================
     */

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    /*
     * ========================================================
     * STATUS
     * ========================================================
     */

    status: {
      type: String,
      enum: [
        "DRAFT",
        "ACTIVE",
        "ARCHIVED",
        "REJECTED",
      ],
      default: "ACTIVE",
      index: true,
    },

    /*
     * ========================================================
     * USAGE / QUALITY METADATA
     * ========================================================
     */

    timesUsed: {
      type: Number,
      default: 0,
      min: 0,
    },

    lastUsedAt: {
      type: Date,
      default: null,
    },

    /*
     * Used by import/review workflows.
     */
    importBatchId: {
      type: String,
      default: "",
      trim: true,
      index: true,
    },
  },
  {
    timestamps: true,
  },
);

/*
 * ============================================================
 * DUPLICATE QUESTION PROTECTION
 * ============================================================
 *
 * Same educator cannot insert the same normalized question
 * hash twice.
 *
 * This is intentionally scoped to the creator because two
 * educators may independently maintain equivalent questions.
 */
educatorQuestionSchema.index(
  {
    createdBy: 1,
    questionHash: 1,
  },
  {
    unique: true,
  },
);

educatorQuestionSchema.index({
  createdBy: 1,
  subject: 1,
  topic: 1,
  difficulty: 1,
  status: 1,
});

educatorQuestionSchema.index({
  createdBy: 1,
  questionCode: 1,
});

module.exports =
  mongoose.models.EducatorQuestion ||
  mongoose.model(
    "EducatorQuestion",
    educatorQuestionSchema,
  );